language: python
python:
  - "2.7"
  - "3.2"
  - "3.4"

# command to install dependencies
install:
    - pip install -r requirements_python`python version.py`.txt --use-mirrors

# command to run tests
script: make test