language: python
python:
  - "2.7"
  - "3.2"

# command to install dependencies
install: pip install -r requirements_python`python version.py`.txt --use-mirrors

# command to run tests
script: nosetests && sphinx-build -nW -b html -d docs/_build/doctrees docs docs/_build/html